language: cpp

compiler:
  - gcc

install:
  - sudo apt-get install libgtest-dev cmake

before_script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..

script: make && ./sqrt_test && ./dailycodingproblem1_test

