language: cpp

compiler:
  - gcc

install:
  - sudo apt-get install libgtest-dev cmake lcov

before_script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_FLAGS="-g --coverage" ..

script: make test 

after_success:
# Create lcov report
- lcov --capture --directory . --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
- lcov --list coverage.info # debug info
# Uploading report to CodeCov
- CODECOV_TOKEN="d0817f62-7b55-4de7-9e7c-61443f124d32"
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
